### ISSUE TITLE
Getting Job Progress occassionally hangs

### ISSUE THREAD

**Issue by isaac2004** [Azure/azure-sdk-for-media-services-extensions#29]
I have seen this happen multiple times, but have never been able to find a reason. I have a callback function that looks like so

`  job = job.StartExecutionProgressTask(
                j =>
                {
                    JobStateChanged(job, type);
                },
                CancellationToken.None).Result;

```
    void JobStateChanged(IJob job, string type)
    {
        ConsoleColor clr = Console.ForegroundColor;
        Console.ForegroundColor = ConsoleColor.Green;
        Console.WriteLine("{0}: {1} State: {2}", DateTime.Now.ToLongTimeString(), job.Name, job.State);
        Console.WriteLine("Job progress: {0:0.##}%", job.GetOverallProgress());
        Console.ForegroundColor = clr;
    }
```

`

What I notice is that when a job finishes, the JobStateChange event is not firing, even though it finishes if I look in the poral (or in Azure Media Explorer). Is there some retry or catch logic that I can implement to ensure I can handle this state change issue accordingly?

**Comment by johndeu** [comment]
have you tried using Notifications through Queues yet?  More reliable through the Queue.
