### ISSUE TITLE
It appears that the latest version doesn't include the GetMetadata method

### ISSUE THREAD

**Issue by JohnGalt1717** [Azure/azure-sdk-for-media-services-extensions#32]
This appears to have been dropped for some reason (and has broken our code!) on both the Asset and the Asset files.

Please bring it back.

**Comment by johndeu** [comment]
Roll back to version v3.3.0.  There is a broken build right now in 3.5.2. 
We are working on getting the build fixed.

**Comment by mconverti** [comment]
@JohnGalt1717 please try again with the latest version of the windowsazure.mediaservices.extensions nuget package (v3.7.0.1). The issue should be fixed now.

Thanks,
Mariano

**Comment by JohnGalt1717** [comment]
Working again!

**Comment by johndeu** [comment]
Awesome! Thanks
